// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo7j-TrcAS8sDC6YYHgIWEA6mUrtg1uiU',
    appId: '1:215949729227:web:3d9c5b344d2302d1a9aa4e',
    messagingSenderId: '215949729227',
    projectId: 'flash-chat-4162c',
    authDomain: 'flash-chat-4162c.firebaseapp.com',
    storageBucket: 'flash-chat-4162c.appspot.com',
    measurementId: 'G-LVC4CC0M7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC20c6FFdSZYbExdGkE02Jgcy001im3Evk',
    appId: '1:215949729227:android:eda52e975d89e7e6a9aa4e',
    messagingSenderId: '215949729227',
    projectId: 'flash-chat-4162c',
    storageBucket: 'flash-chat-4162c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9rDjraY56Jpi5hb9hzp5G4GJcPgjP8ZM',
    appId: '1:215949729227:ios:916cc64e051194e7a9aa4e',
    messagingSenderId: '215949729227',
    projectId: 'flash-chat-4162c',
    storageBucket: 'flash-chat-4162c.appspot.com',
    iosBundleId: 'com.example.messaging',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9rDjraY56Jpi5hb9hzp5G4GJcPgjP8ZM',
    appId: '1:215949729227:ios:e36c770c48f0c405a9aa4e',
    messagingSenderId: '215949729227',
    projectId: 'flash-chat-4162c',
    storageBucket: 'flash-chat-4162c.appspot.com',
    iosBundleId: 'com.example.messaging.RunnerTests',
  );
}
